### ISSUE TITLE
Semantics of `Cat`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/mkr-mcd-spec#54]

**Comment by gtrepta** [comment]
`Cat . bite` makes a call to `Vow . fess`, so the `CDP-CORE` module would need to import `SYSTEM-STABILIZER`. However, `SYSTEM-STABILIZER` is already importing `CDP-CORE`, which would cause a circular dependency.

Also, the Vow semantics were written a while before we made many changes such as implementing Rat, parameterized productions, etc. Cat makes a call to Vat as well as use some of its data. It may be a good idea to go through Vat and get it up to date before we implement Cat, otherwise we would have to also update Cat when we update Vat.

**Comment by dwightguth** [comment]
I think the correct solution to the circular dependency is to move each contract into its own file.

**Comment by ehildenb** [comment]
I agree, let's do one file per contract instead of trying to group them.
